"""Constants for the Jebao Aqua Pump integration."""

from datetime import timedelta
import logging

DOMAIN = "jebao_aqua"

LOGGER = logging.getLogger(__package__)
LOGGER.setLevel(logging.DEBUG)

# API constants
GIZWITS_APP_ID = "c3703c4888ec4736a3a0d9425c321604"  # This is used by the Android app, iOS may use a different one?

# Gizwits API URLs by Region
GIZWITS_API_URLS = {
    "eu": {
        "LOGIN_URL": "https://euaepapp.gizwits.com/app/smart_home/login/pwd",
        "DEVICES_URL": "https://euapi.gizwits.com/app/bindings",
        "DEVICE_DATA_URL": "https://euapi.gizwits.com/app/devdata/{device_id}/latest",
        "CONTROL_URL": "https://euapi.gizwits.com/app/control/{device_id}",
    },
    "us": {
        "LOGIN_URL": "https://usaepapp.gizwits.com/app/smart_home/login/pwd",
        "DEVICES_URL": "https://usapi.gizwits.com/app/bindings",
        "DEVICE_DATA_URL": "https://usapi.gizwits.com/app/devdata/{device_id}/latest",
        "CONTROL_URL": "https://usapi.gizwits.com/app/control/{device_id}",
    },
    "cn": {
        "LOGIN_URL": "https://aep-app.gizwits.com/app/smart_home/login/pwd",
        "DEVICES_URL": "https://api.gizwits.com/app/bindings",
        "DEVICE_DATA_URL": "https://api.gizwits.com/app/devdata/{device_id}/latest",
        "CONTROL_URL": "https://api.gizwits.com/app/control/{device_id}",
    },
}

GITHUB_ISSUE_URL = "https://github.com/chrisc123/jebao_aqua-homeassistant/issues"
MODEL_CHECK_FAILED = "missing_model"

TIMEOUT = 10
DISCOVERY_TIMEOUT = 5  # seconds

LAN_PORT = 12416

UPDATE_INTERVAL = timedelta(seconds=2)
UPDATE_INTERVAL = timedelta(seconds=2)

# Platform types
PLATFORMS = ["number", "select", "sensor", "switch"]

# Default Region (used if no region is specified)
DEFAULT_REGION = "eu"

# Service Map (Country Code to Region)
SERVICE_MAP = {
    "CN": "cn",
    "JP": "us",
    "US": "us",
    "CA": "us",
    "GB": "eu",
    "FR": "eu",
    "DE": "eu",
    "DZ": "eu",
    "AF": "us",
    "AR": "us",
    "AE": "us",
    "SY": "us",
    "AW": "us",
    "OM": "us",
    "AZ": "us",
    "EG": "eu",
    "ET": "eu",
    "IE": "eu",
    "EE": "eu",
    "AD": "eu",
    "AO": "eu",
    "AI": "us",
    "AG": "us",
    "AT": "eu",
    "AX": "eu",
    "AU": "us",
    "MO": "us",
    "BB": "us",
    "PG": "us",
    "BS": "us",
    "PK": "us",
    "PY": "us",
    "PS": "us",
    "BH": "us",
    "PA": "us",
    "BR": "us",
    "BY": "eu",
    "BM": "us",
    "BG": "eu",
    "MP": "us",
    "BJ": "eu",
    "BE": "eu",
    "IS": "us",
    "PR": "us",
    "PL": "eu",
    "BA": "eu",
    "BO": "us",
    "BZ": "us",
    "BW": "eu",
    "BQ": "us",
    "BT": "us",
    "BF": "eu",
    "BI": "eu",
    "KP": "us",
    "GQ": "eu",
    "DK": "eu",
    "TL": "us",
    "TG": "eu",
    "DM": "us",
    "DO": "us",
    "RU": "eu",
    "EC": "us",
    "ER": "eu",
    "FO": "us",
    "PF": "us",
    "GF": "us",
    "TF": "eu",
    "PH": "us",
    "FJ": "us",
    "FI": "eu",
    "CV": "us",
    "FK": "us",
    "GM": "eu",
    "CG": "eu",
    "CD": "eu",
    "CO": "us",
    "CR": "us",
    "GD": "us",
    "GL": "us",
    "GE": "us",
    "GG": "eu",
    "CU": "us",
    "GP": "us",
    "GU": "us",
    "GY": "us",
    "KZ": "us",
    "HT": "us",
    "KR": "us",
    "NL": "eu",
    "ME": "eu",
    "HN": "us",
    "TR": "us",
    "KI": "us",
    "DJ": "eu",
    "KG": "us",
    "GN": "eu",
    "GW": "eu",
    "GH": "eu",
    "GA": "eu",
    "KH": "us",
    "VA": "eu",
    "CZ": "eu",
    "ZW": "eu",
    "CM": "eu",
    "QA": "us",
    "KY": "us",
    "CC": "eu",
    "KM": "eu",
    "CI": "eu",
    "KW": "us",
    "HR": "eu",
    "KE": "eu",
    "CK": "us",
    "CW": "us",
    "LV": "eu",
    "LS": "eu",
    "LA": "us",
    "LB": "us",
    "LT": "eu",
    "LR": "eu",
    "LY": "eu",
    "LI": "eu",
    "LU": "eu",
    "RW": "eu",
    "RO": "eu",
    "MG": "eu",
    "IM": "eu",
    "MV": "eu",
    "MT": "eu",
    "MW": "eu",
    "MY": "us",
    "ML": "eu",
    "MK": "eu",
    "MH": "us",
    "MQ": "us",
    "YT": "eu",
    "MU": "eu",
    "MR": "eu",
    "UM": "us",
    "AS": "us",
    "VI": "us",
    "MN": "us",
    "MS": "us",
    "BD": "us",
    "PE": "us",
    "FM": "us",
    "MM": "us",
    "MD": "eu",
    "MA": "eu",
    "MC": "eu",
    "MZ": "eu",
    "MX": "us",
    "NA": "eu",
    "ZA": "eu",
    "AQ": "us",
    "GS": "us",
    "SS": "eu",
    "NR": "us",
    "NP": "us",
    "NI": "us",
    "NE": "eu",
    "NG": "eu",
    "NU": "us",
    "NO": "eu",
    "NF": "us",
    "PW": "us",
    "PN": "us",
    "PT": "us",
    "SE": "eu",
    "CH": "eu",
    "EH": "eu",
    "SV": "us",
    "WS": "us",
    "RS": "eu",
    "SL": "eu",
    "SN": "eu",
    "CY": "us",
    "SC": "eu",
    "SA": "us",
    "BL": "us",
    "CX": "eu",
    "ST": "eu",
    "SH": "us",
    "KN": "us",
    "LC": "us",
    "MF": "us",
    "SX": "us",
    "SM": "eu",
    "PM": "us",
    "VC": "us",
    "LK": "us",
    "SK": "eu",
    "SI": "eu",
    "SJ": "us",
    "SZ": "eu",
    "SD": "eu",
    "SR": "us",
    "SB": "us",
    "SO": "eu",
    "TJ": "us",
    "TW": "us",
    "TH": "us",
    "TZ": "eu",
    "TO": "us",
    "TC": "us",
    "TT": "us",
    "TN": "eu",
    "TV": "us",
    "TM": "us",
    "RE": "cn",
    "TK": "us",
    "WF": "us",
    "VU": "us",
    "GT": "us",
    "VE": "us",
    "BN": "us",
    "UG": "eu",
    "UA": "eu",
    "UY": "us",
    "UZ": "us",
    "ES": "eu",
    "GR": "eu",
    "HK": "us",
    "SG": "us",
    "NC": "us",
    "NZ": "us",
    "JE": "eu",
    "HU": "eu",
    "JM": "us",
    "AM": "us",
    "YE": "us",
    "IQ": "us",
    "IR": "us",
    "IL": "us",
    "IT": "eu",
    "IN": "eu",
    "ID": "us",
    "VG": "us",
    "IO": "eu",
    "JO": "us",
    "VN": "us",
    "ZM": "eu",
    "TD": "eu",
    "GI": "eu",
    "CL": "us",
    "CF": "eu",
}
